// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Run4Cause.Data;

#nullable disable

namespace Run4Cause.Migrations
{
    [DbContext(typeof(Run4CauseContext))]
    [Migration("20220331084341_ChangeTotalDistanceCoveredType")]
    partial class ChangeTotalDistanceCoveredType
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EditionRun", b =>
                {
                    b.Property<int>("EditionsId")
                        .HasColumnType("integer")
                        .HasColumnName("editions_id");

                    b.Property<int>("RunsId")
                        .HasColumnType("integer")
                        .HasColumnName("runs_id");

                    b.HasKey("EditionsId", "RunsId")
                        .HasName("pk_edition_run");

                    b.HasIndex("RunsId")
                        .HasDatabaseName("ix_edition_run_runs_id");

                    b.ToTable("edition_run", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Edition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headline");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("Location")
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_editions");

                    b.ToTable("editions", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EditionId")
                        .HasColumnType("integer")
                        .HasColumnName("edition_id");

                    b.Property<DateTime>("Register")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("register");

                    b.Property<int>("RunId")
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("EditionId")
                        .HasDatabaseName("ix_entries_edition_id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_entries_run_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_entries_user_id");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<List<string>>("Photos")
                        .HasColumnType("text[]")
                        .HasColumnName("photos");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_user_id");

                    b.ToTable("profiles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Maiores, vero!",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Run4Cause.Models.Run", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_runs");

                    b.ToTable("runs", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.RunWaypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Instant")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant");

                    b.Property<int>("RunId")
                        .HasColumnType("integer")
                        .HasColumnName("run_id");

                    b.Property<int>("WaypointId")
                        .HasColumnType("integer")
                        .HasColumnName("waypoint_id");

                    b.HasKey("Id")
                        .HasName("pk_run_waypoints");

                    b.HasIndex("RunId")
                        .HasDatabaseName("ix_run_waypoints_run_id");

                    b.HasIndex("WaypointId")
                        .HasDatabaseName("ix_run_waypoints_waypoint_id");

                    b.ToTable("run_waypoints", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Sponsorship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AmountPerKilometer")
                        .HasColumnType("real")
                        .HasColumnName("amount_per_kilometer");

                    b.Property<int?>("PerformerId")
                        .HasColumnType("integer")
                        .HasColumnName("performer_id");

                    b.Property<int?>("SponsorId")
                        .HasColumnType("integer")
                        .HasColumnName("sponsor_id");

                    b.HasKey("Id")
                        .HasName("pk_sponsorships");

                    b.HasIndex("PerformerId")
                        .HasDatabaseName("ix_sponsorships_performer_id");

                    b.HasIndex("SponsorId")
                        .HasDatabaseName("ix_sponsorships_sponsor_id");

                    b.ToTable("sponsorships", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Tracking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Instant")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("instant");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("WaypointId")
                        .HasColumnType("integer")
                        .HasColumnName("waypoint_id");

                    b.HasKey("Id")
                        .HasName("pk_trackings");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trackings_user_id");

                    b.HasIndex("WaypointId")
                        .HasDatabaseName("ix_trackings_waypoint_id");

                    b.ToTable("trackings", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Trophy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_trophy");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_trophy_user_id");

                    b.ToTable("trophy", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("profile_id");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<decimal?>("TotalDistanceCovered")
                        .HasColumnType("numeric(20,2)")
                        .HasColumnName("total_distance_covered");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7b5d7e33-2f17-490c-b4e6-44d9c4ebb912",
                            Email = "alexandre.philibert@cpnv.ch",
                            EmailConfirmed = false,
                            FirstName = "Alexandre",
                            LastName = "Philibert",
                            LockoutEnabled = false,
                            PhoneNumber = "0781234567",
                            PhoneNumberConfirmed = false,
                            TotalDistanceCovered = 12.4m,
                            TwoFactorEnabled = false
                        });
                });

            modelBuilder.Entity("Run4Cause.Models.UserLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_logins");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Run4Cause.Models.Waypoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_waypoints");

                    b.ToTable("waypoints", (string)null);
                });

            modelBuilder.Entity("EditionRun", b =>
                {
                    b.HasOne("Run4Cause.Models.Edition", null)
                        .WithMany()
                        .HasForeignKey("EditionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_run_editions_editions_id");

                    b.HasOne("Run4Cause.Models.Run", null)
                        .WithMany()
                        .HasForeignKey("RunsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_edition_run_runs_runs_id");
                });

            modelBuilder.Entity("Run4Cause.Models.Entry", b =>
                {
                    b.HasOne("Run4Cause.Models.Edition", "Edition")
                        .WithMany("Entries")
                        .HasForeignKey("EditionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entries_editions_edition_id");

                    b.HasOne("Run4Cause.Models.Run", "Run")
                        .WithMany("Entries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entries_runs_run_id");

                    b.HasOne("Run4Cause.Models.User", "User")
                        .WithMany("Entries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entries_users_user_id");

                    b.Navigation("Edition");

                    b.Navigation("Run");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Run4Cause.Models.Profile", b =>
                {
                    b.HasOne("Run4Cause.Models.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("Run4Cause.Models.Profile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_profiles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Run4Cause.Models.RunWaypoint", b =>
                {
                    b.HasOne("Run4Cause.Models.Run", "Run")
                        .WithMany("RunWaypoints")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_waypoints_runs_run_id");

                    b.HasOne("Run4Cause.Models.Waypoint", "Waypoint")
                        .WithMany("RunWaypoints")
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_run_waypoints_waypoints_waypoint_id");

                    b.Navigation("Run");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("Run4Cause.Models.Sponsorship", b =>
                {
                    b.HasOne("Run4Cause.Models.User", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerId")
                        .HasConstraintName("fk_sponsorships_users_performer_id");

                    b.HasOne("Run4Cause.Models.User", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .HasConstraintName("fk_sponsorships_users_sponsor_id");

                    b.Navigation("Performer");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("Run4Cause.Models.Tracking", b =>
                {
                    b.HasOne("Run4Cause.Models.User", "User")
                        .WithMany("Trackings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trackings_users_user_id");

                    b.HasOne("Run4Cause.Models.Waypoint", "Waypoint")
                        .WithMany("Trackings")
                        .HasForeignKey("WaypointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_trackings_waypoints_waypoint_id");

                    b.Navigation("User");

                    b.Navigation("Waypoint");
                });

            modelBuilder.Entity("Run4Cause.Models.Trophy", b =>
                {
                    b.HasOne("Run4Cause.Models.User", null)
                        .WithMany("Trophies")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_trophy_users_user_id");
                });

            modelBuilder.Entity("Run4Cause.Models.Edition", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Run4Cause.Models.Run", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("RunWaypoints");
                });

            modelBuilder.Entity("Run4Cause.Models.User", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("Profile");

                    b.Navigation("Trackings");

                    b.Navigation("Trophies");
                });

            modelBuilder.Entity("Run4Cause.Models.Waypoint", b =>
                {
                    b.Navigation("RunWaypoints");

                    b.Navigation("Trackings");
                });
#pragma warning restore 612, 618
        }
    }
}
